### ISSUE TITLE
Setup continues deployment

### ISSUE THREAD

**Issue by Jaxwood** [Jaxwood/easv#3]
Add deploy section to the `.travis.yml` file.

Update the name-slot value.

```yml
deploy:
  - provider: azure_web_apps
    slot: name-slot
    on: develop
  - provider: azure_web_apps
    slot: name-slot
    on: release
  - provider: azure_web_apps
    on: master
```
